import React, { useState, useEffect } from "react";
import Head from 'next/head';
import ImageCall from '@/components/artPiece';
import { useQuery } from "react-query";

export default function Home() {
  const { data, isLoading } = useQuery('artworks', async () => {
    await new Promise(resolve => setTimeout(resolve, 2000));

    const response = await fetch('https://api.artic.edu/api/v1/artworks?page=1&limit=50');
    if (!response.ok) {
      throw new Error('Network response was not ok');
    }
    return response.json();
  });

  if (isLoading) {
    return <div>Loading...</div>;
  }

  const artworks = data?.data || [];

  console.log(artworks, isLoading);



  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ImageCall name={null} />
      {artworks.map(artwork => (
        <li key={artwork.id}>{artwork.title}</li>
      ))}
    </>
  );
}
